name: GitLab Mirror

on:
  push:
  workflow_dispatch:
  schedule: 
    - cron: '30 */3 * * *'

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  Gitab_Mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0

      - name: Push
        env:
          GL_TOKEN: ${{ secrets.GL_TOKEN }}
          GL_URL: ${{ secrets.GL_URL }}
        run: |
          git config --global user.email "astroashwin@outlook.com"
          git config --global user.name "Ashwin Devi Srinivasan"
          git push -f $GL_URL ${GITHUB_REF##*/}:${GITHUB_REF##*/} 