name: JSON Linting
on:
  push:
  workflow_dispatch:

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
          ref: fourteen

      - name: Lint
        run: sudo -E python3 .github/scripts/jsonValidator

      - name: Commit and Push Changes
        run: sudo bash .github/scripts/jsonValidator/push.sh