name: Poster
on:
  push:
  workflow_dispatch:

env:
  BOT_API: ${{ secrets.BOT_API }}
  TOKEN: ${{ secrets.TOKEN }}
  SF_PASS: ${{ secrets.SF_PASS }}

jobs:
  postman:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dep
        run: sudo pip install python-telegram-bot

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: twelve

      - name: Bot
        run: sudo -E python3 .github/scripts/UpdatePoster

      - name: Checkout Releases Public
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ secrets.DOWNLOADS_REPO }}
          path: releases-public

      - name: Checkout Releases
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ secrets.CI_REPO }}
          path: releases

      - name: Uploader
        run: sudo -E python3 .github/scripts/Uploader
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Commit and Push Changes
        run: sudo bash .github/scripts/push.sh