name: Update devices json and device list

on:
  push:
    paths:
      - .github/workflows/regen_devices.yaml
      - API/**
  workflow_dispatch:

jobs:
  clone:
    runs-on: ubuntu-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Regen devices json and device list
        run: python3 .github/scripts/regen_devices.py

      - name: Commit to repo
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit_message: "[CI] Regen devices.json and DeviceList.md"
          file_pattern: "API/devices.json docs/DeviceList.md"

      - name: Wait for cache
        run: sleep 10

      - name: Revalidate website
        env:
          TOKEN: ${{ secrets.REVALIDATION_SECRET }}
          BYPASS_TOKEN: ${{ secrets.CF_BYPASS_TOKEN }}
        run: |
          curl -X POST https://www.pixelos.net/api/revalidate \
            -H "Authorization: Bearer $TOKEN" \
            -H "cf-bypass: $BYPASS_TOKEN" \
            -H "Content-Type: application/json" \
            -H "User-Agent: GitHub-Actions" \
            -d '{"target": "all"}'
