name: Update devices json

on:
  push:
    paths:
      - .github/workflows/regen_devices.yaml
      - API/devices/*
  workflow_dispatch:

jobs:
  clone:
    runs-on: ubuntu-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Regen devices json
        run: python3 .github/scripts/regen_devices.py

      - name: Commit to repo
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit_message: "[CI] Regen devices.json"
          file_pattern: "API/devices.json"
